Repository nonebot/noneflow, pull requests merged in 2024-11, with the labels that each got.

#246 fix: 修复未正常同步商店数据的问题
  CHANGELOG.md
  src/providers/store_test/store.py
  src/providers/store_test/validation.py
  tests/conftest.py
  tests/utils/store_test/output.json
  tests/utils/store_test/output_failed.json
  tests/utils/store_test/store/store_adapters.json
  tests/utils/store_test/store/store_bots.json
  tests/utils/store_test/store/store_drivers.json
  tests/utils/store_test/store/store_plugins.json
  tests/utils/store_test/test_store_sync.py
  tests/utils/store_test/test_store_test.py
  tests/utils/store_test/test_validate_plugin.py
Labels: bug

#249 fix: 禁用 store 和 registry 模型中 tag 的验证
  src/providers/models.py
  tests/utils/store_test/store/store_plugins.json
  tests/utils/store_test/test_store_sync.py
  tests/utils/store_test/test_store_test.py
Labels: bug, skip-changelog

#252 fix: 修复 update_file 函数数据序列化问题
  src/plugins/github/plugins/remove/utils.py
  src/plugins/github/plugins/remove/validation.py
  tests/github/remove/utils/test_remove_resolve_pull_requests.py
  tests/github/remove/utils/test_update_file.py
Labels: bug, skip-changelog

#255 fix: rule 新增 is_publish_related_workflow
  src/plugins/github/depends/__init__.py
  src/plugins/github/plugins/publish/__init__.py
  tests/github/publish/process/test_auto_merge.py
  tests/github/publish/process/test_publish_check.py
  tests/github/publish/process/test_publish_pull_request.py
  tests/github/remove/process/test_remove_check.py
  tests/github/remove/process/test_remove_pull_request.py
Labels: bug, skip-changelog

#259 feat: 商店存放 json5 格式的数据
  CHANGELOG.md
  examples/noneflow.yml
  pyproject.toml
  src/plugins/github/plugins/publish/utils.py
  src/plugins/github/plugins/remove/utils.py
  src/plugins/github/plugins/remove/validation.py
  src/plugins/github/utils.py
  src/providers/constants.py
  src/providers/docker_test/plugin_test.py
  src/providers/store_test/store.py
  src/providers/store_test/utils.py
  src/providers/utils.py
  tests/github/publish/utils/test_publish_resolve_conflict_pull_requests.py
  tests/github/remove/utils/test_update_file.py
  tests/github/utils.py
  tests/utils/store_test/conftest.py
  tests/utils/store_test/store/store_adapters.json5
  tests/utils/store_test/store/store_bots.json5
  tests/utils/store_test/store/store_drivers.json5
  tests/utils/store_test/store/store_plugins.json5
  tests/utils/store_test/test_utils.py
  tests/utils/test_json5.py
  uv.lock
Labels: enhancement

#260 fix: 修复 json5 无法正常加载的问题
  src/plugins/github/plugins/publish/validation.py
  tests/conftest.py
  tests/github/publish/process/test_publish_check.py
  tests/github/publish/utils/test_publish_resolve_conflict_pull_requests.py
  tests/github/remove/process/test_remove_check.py
  tests/github/remove/utils/test_remove_resolve_pull_requests.py
  tests/github/remove/utils/test_update_file.py
Labels: bug, skip-changelog

#262 fix: 将 load_json 函数统一为 json5
  src/plugins/github/plugins/publish/utils.py
  src/plugins/github/plugins/publish/validation.py
  src/plugins/github/plugins/remove/validation.py
  src/providers/docker_test/__init__.py
  src/providers/store_test/store.py
  src/providers/store_test/utils.py
  src/providers/utils.py
  src/providers/validation/models.py
  src/providers/validation/utils.py
  tests/utils/store_test/test_utils.py
Labels: skip-changelog

#266 fix: 修复解决冲突验证失败时未能正常跳过的问题
  src/plugins/github/plugins/publish/utils.py
  src/plugins/github/plugins/remove/utils.py
  tests/github/publish/utils/test_publish_resolve_conflict_pull_requests.py
  tests/github/remove/utils/test_remove_resolve_pull_requests.py
  tests/github/remove/utils/test_update_file.py
Labels: bug, skip-changelog

#267 build: 手动指定 project 目录
  Dockerfile
Labels: bug

#269 fix(store_test): 修复商店测试中获取 PyPI 数据出错会直接退出的问题
  CHANGELOG.md
  src/providers/store_test/store.py
  src/providers/store_test/utils.py
  tests/utils/store_test/test_store_test.py
Labels: bug

#270 fix: 修复 Docker Test 输出不完善的问题
  src/providers/docker_test/plugin_test.py
Labels: bug

#268 fix(store_test): 修复商店测试时出现缺少 author_id 报错的问题
  CHANGELOG.md
  src/providers/store_test/validation.py
  tests/utils/store_test/test_validate_plugin.py
Labels: bug

#273 feat(plugin_test): 简化插件测试输出
  CHANGELOG.md
  src/providers/docker_test/plugin_test.py
Labels: enhancement

#274 feat: 重新加回作业摘要
  .env
  CHANGELOG.md
  src/plugins/github/config.py
  src/plugins/github/plugins/publish/validation.py
  tests/conftest.py
  tests/github/publish/utils/test_validate_info_from_issue.py
Labels: enhancement

#276 fix(docker_test): 修复 Docker 容器测试后未正常清理的问题
  CHANGELOG.md
  src/providers/docker_test/__init__.py
  tests/utils/docker_test/test_docker_plugin_test.py
Labels: bug

#277 fix(store_test): 修复商店测试时标签验证出错的问题
  CHANGELOG.md
  src/plugins/github/plugins/publish/validation.py
  src/providers/validation/__init__.py
  src/providers/validation/models.py
  tests/github/publish/utils/test_validate_info_from_issue.py
  tests/utils/store_test/test_validate_plugin.py
Labels: bug

#279 fix(plugin_test): 修复创建环境报错时无法匹配到版本号的问题
  CHANGELOG.md
  pyproject.toml
  src/providers/docker_test/plugin_test.py
  src/providers/store_test/validation.py
  tests/utils/docker_test/test_extract_version.py
  tests/utils/store_test/test_extract_version.py
Labels: bug

#280 fix(docker_test): 修复插件测试获取到的插件元数据主页为空时报错的问题
  CHANGELOG.md
  src/providers/docker_test/__init__.py
  tests/utils/docker_test/test_docker_plugin_test.py
Labels: bug

#281 fix(plugin_test): 使用规范化的名称匹配插件版本号
  CHANGELOG.md
  src/providers/docker_test/plugin_test.py
  tests/utils/docker_test/test_extract_version.py
Labels: bug

#283 fix(docker_test): 修复插件元数据异常时导致插件测试验证报错的问题
  CHANGELOG.md
  src/plugins/github/plugins/publish/render.py
  src/plugins/github/plugins/publish/validation.py
  src/providers/docker_test/__init__.py
  src/providers/docker_test/plugin_test.py
  src/providers/models.py
  src/providers/store_test/validation.py
  tests/utils/docker_test/test_docker_plugin_test.py
  tests/utils/store_test/output.json
  tests/utils/store_test/output_failed.json
  tests/utils/store_test/test_validate_plugin.py
  tests/utils/validation/test_plugin.py
Labels: bug

#282 fix(docker_test): 修复插件测试无法安装部分依赖的问题
  CHANGELOG.md
  src/providers/docker_test/Dockerfile
Labels: bug

#284 fix(plugin_test): 修复插件元数据不合法时 metadata.json 为空的问题
  CHANGELOG.md
  src/providers/docker_test/plugin_test.py
Labels: bug

#289 fix: 修复发布后 registry_update 中版本号为默认值的问题
  CHANGELOG.md
  src/plugins/github/plugins/publish/validation.py
  src/providers/store_test/store.py
  src/providers/store_test/utils.py
  src/providers/store_test/validation.py
  src/providers/utils.py
  src/providers/validation/models.py
  tests/conftest.py
  tests/github/publish/process/test_publish_pull_request.py
  tests/github/publish/utils/test_publish_resolve_conflict_pull_requests.py
  tests/github/publish/utils/test_trigger_registry_update.py
  tests/utils/store_test/test_utils.py
Labels: bug

#288 feat: 从插件测试中提取环境信息
  src/providers/docker_test/__init__.py
  src/providers/docker_test/plugin_test.py
  tests/utils/docker_test/test_docker_plugin_test.py
  tests/utils/docker_test/test_parse_requirements.py
  tests/utils/docker_test/test_plugin_test.py
Labels: enhancement

#291 fix(plugin_test): 超时后仍需读取 stdout 与 stderr 的内容
  CHANGELOG.md
  src/providers/docker_test/plugin_test.py
Labels: bug

#295 feat: 支持修改配置并重新测试
  CHANGELOG.md
  src/plugins/github/constants.py
  src/plugins/github/plugins/config/__init__.py
  src/plugins/github/plugins/config/constants.py
  src/plugins/github/plugins/config/utils.py
  src/plugins/github/plugins/publish/__init__.py
  src/providers/utils.py
  tests/github/config/conftest.py
  tests/github/config/process/test_config_auto_merge.py
  tests/github/config/process/test_config_check.py
  tests/github/config/utils.py
  tests/github/config/utils/test_config_update_file.py
Labels: enhancement

#296 fix(docker_test): 修复 Docker Test 报错未捕获的问题
  CHANGELOG.md
  src/plugins/github/plugins/config/utils.py
  src/plugins/github/plugins/publish/validation.py
  src/providers/docker_test/__init__.py
  src/providers/docker_test/plugin_test.py
  src/providers/store_test/validation.py
  tests/github/config/process/test_config_check.py
  tests/github/publish/process/test_publish_pull_request.py
  tests/github/publish/utils/test_publish_resolve_conflict_pull_requests.py
  tests/github/publish/utils/test_trigger_registry_update.py
  tests/github/publish/utils/test_validate_info_from_issue.py
  tests/utils/docker_test/test_docker_plugin_test.py
  tests/utils/docker_test/test_plugin_test.py
  tests/utils/store_test/output.json
  tests/utils/store_test/output_failed.json
Labels: bug

#294 feat: 添加测试中的提示
  CHANGELOG.md
  src/plugins/github/models/issue.py
  src/plugins/github/plugins/publish/__init__.py
  src/plugins/github/plugins/publish/constants.py
  src/plugins/github/plugins/publish/utils.py
  tests/github/publish/process/test_publish_check.py
  tests/github/publish/utils/test_ensure_issue_plugin_test_button.py
Labels: enhancement

#297 feat: 为商店测试新增步骤总结与使用 logging 格式化日志
  src/providers/logger.py
  src/providers/store_test/__main__.py
  src/providers/store_test/store.py
  src/providers/store_test/validation.py
  src/providers/utils.py
  tests/utils/store_test/test_step_summary.py
Labels: enhancement

#298 fix: 修复插件测试结果中插件元数据 description 字段名称不正确的问题
  CHANGELOG.md
  src/providers/models.py
  tests/github/config/process/test_config_check.py
  tests/github/config/utils/test_config_update_file.py
  tests/github/publish/process/test_publish_pull_request.py
  tests/github/publish/utils/test_trigger_registry_update.py
Labels: bug

#299 fix(github/config): 补上插件测试按钮
  src/plugins/github/plugins/config/__init__.py
  tests/github/config/process/test_config_check.py
Labels: bug, skip-changelog

#301 fix: 修复 Docker Test 报错后仍无法运行的问题
  CHANGELOG.md
  src/providers/docker_test/__init__.py
  src/providers/validation/constants.py
  tests/utils/docker_test/test_docker_plugin_test.py
  tests/utils/validation/fields/test_missing.py
  tests/utils/validation/utils.py
Labels: bug

#300 fix(plugin_test): 修复插件测试日志不全时版本号匹配失败的问题
  CHANGELOG.md
  src/providers/docker_test/plugin_test.py
  tests/utils/docker_test/test_extract_version.py
Labels: bug
