Repository nonebot/noneflow, pull requests merged in 2025-06, with the labels that each got.

#397 chore(renovate): 更新 Python 版本时还需要更新 pep621 的 python
  .github/renovate.json5
Labels: ci

#398 fix: 修复历史信息的渲染和正则匹配的问题
  src/plugins/github/plugins/publish/__init__.py
  src/plugins/github/plugins/publish/constants.py
  src/plugins/github/plugins/publish/templates/comment.md.jinja
  tests/plugins/github/config/process/test_config_check.py
  tests/plugins/github/publish/process/test_publish_check_plugin.py
  tests/plugins/github/publish/process/test_publish_pull_request.py
  tests/plugins/github/publish/render/test_publish_render.py
  tests/plugins/github/publish/render/test_publish_render_data.py
  tests/plugins/github/publish/render/test_publish_render_error.py
  tests/plugins/github/publish/utils/test_history_workflow.py
  tests/plugins/github/publish/utils/test_trigger_registry_update.py
Labels: bug

#399 fix: 更新文件时手动添加对应文件
  src/plugins/github/handlers/git.py
  src/plugins/github/plugins/config/__init__.py
  src/plugins/github/plugins/config/utils.py
  src/plugins/github/plugins/publish/utils.py
  src/plugins/github/plugins/remove/__init__.py
  src/plugins/github/plugins/remove/utils.py
  tests/plugins/github/config/process/test_config_check.py
  tests/plugins/github/config/utils/test_config_update_file.py
  tests/plugins/github/handlers/test_git_handler.py
  tests/plugins/github/handlers/test_issue_handler.py
  tests/plugins/github/publish/process/test_publish_check.py
  tests/plugins/github/publish/process/test_publish_check_plugin.py
  tests/plugins/github/publish/utils/test_publish_resolve_conflict_pull_requests.py
  tests/plugins/github/remove/process/test_remove_check.py
  tests/plugins/github/remove/utils/test_remove_resolve_pull_requests.py
  tests/plugins/github/remove/utils/test_update_file.py
  tests/plugins/github/resolve/test_resolve_pull_request.py
  uv.lock
Labels: bug

#404 feat: 上传 artifact 无文件时忽略并新增了一些日志
  README.md
  examples/noneflow.yml
  src/plugins/github/handlers/github.py
  src/plugins/github/plugins/publish/constants.py
  src/plugins/github/plugins/publish/utils.py
  src/plugins/github/plugins/publish/validation.py
  tests/plugins/github/handlers/test_github_handler.py
  tests/plugins/github/publish/utils/test_get_noneflow_artifact.py
Labels: enhancement

#405 fix: 修复插件测试和注册更新的条件判断逻辑
  examples/store-test.yml
Labels: bug

#409 fix: 修复机器人/适配器发布时没有历史测试的问题
  CHANGELOG.md
  src/plugins/github/plugins/publish/render.py
  tests/plugins/github/publish/process/test_publish_check.py
  tests/plugins/github/publish/render/test_publish_render.py
  tests/plugins/github/publish/render/test_publish_render_data.py
  tests/plugins/github/publish/render/test_publish_render_error.py
Labels: bug
